/**
 * Represents the role of a participant in a conversation.
 *
 * - `'system'` - System-level instructions that guide the model's behavior.
 * - `'user'` - A message from the end user.
 * - `'assistant'` - A response generated by the model.
 * - `'tool'` - The result of a tool invocation.
 */
export type Role = 'system' | 'user' | 'assistant' | 'tool'

/**
 * Represents a tool invocation requested by the model.
 *
 * @example
 * ```ts
 * const call: ToolCall = {
 *   id: 'call_abc123',
 *   name: 'get_weather',
 *   arguments: { city: 'Berlin' },
 * }
 * ```
 */
export interface ToolCall {
    /** Unique identifier for this tool call, used to match results back to the request. */
    id: string
    /** The name of the tool to invoke. */
    name: string
    /** The parsed arguments to pass to the tool's execute function. */
    arguments: Record<string, unknown>
}

/**
 * A single message in the conversation history exchanged between participants.
 *
 * @example
 * ```ts
 * const userMsg: Message = { role: 'user', content: 'Hello!' }
 * const toolResult: Message = {
 *   role: 'tool',
 *   content: '{"temp": 22}',
 *   toolCallId: 'call_abc123',
 * }
 * ```
 */
export interface Message {
    /** The role of the message author. */
    role: Role
    /** The text content of the message, or `null` when the assistant response consists solely of tool calls. */
    content: string | null
    /** Tool calls requested by the assistant in this message, if any. */
    toolCalls?: ToolCall[]
    /** The ID of the tool call this message is a response to (only for `role: 'tool'`). */
    toolCallId?: string
    /** An optional display name for the message author. */
    name?: string
}
