/**
 * Represents the role of a participant in a conversation.
 *
 * - `'system'` - System-level instructions that guide the model's behavior.
 * - `'user'` - A message from the end user.
 * - `'assistant'` - A response generated by the model.
 * - `'tool'` - The result of a tool invocation.
 */
export type Role = 'system' | 'user' | 'assistant' | 'tool'

/**
 * MIME types supported for image content in tool results.
 */
export type ImageMediaType = 'image/jpeg' | 'image/png' | 'image/gif' | 'image/webp'

/**
 * A structured image result returned by a tool's execute function.
 * When detected in a tool result, the agent loop will format it as a
 * multimodal content block appropriate for the provider (e.g. `image_url`
 * for OpenAI, `image` source for Anthropic, `inlineData` for Gemini).
 *
 * @example
 * ```ts
 * const screenshotTool = defineTool({
 *   name: 'screenshot',
 *   description: 'Capture a screenshot',
 *   parameters: z.object({}),
 *   execute: async () => ({
 *     type: 'image',
 *     mediaType: 'image/jpeg',
 *     data: captureScreenAsBase64(),
 *     text: 'Screenshot captured',
 *   }),
 * })
 * ```
 */
export interface ImageResult {
    /** Discriminator — must be `'image'`. */
    type: 'image'
    /** The MIME type of the image. */
    mediaType: ImageMediaType
    /** Base64-encoded image data. */
    data: string
    /** Optional text to include alongside the image. */
    text?: string
}

/**
 * Represents a tool invocation requested by the model.
 *
 * @example
 * ```ts
 * const call: ToolCall = {
 *   id: 'call_abc123',
 *   name: 'get_weather',
 *   arguments: { city: 'Berlin' },
 * }
 * ```
 */
export interface ToolCall {
    /** Unique identifier for this tool call, used to match results back to the request. */
    id: string
    /** The name of the tool to invoke. */
    name: string
    /** The parsed arguments to pass to the tool's execute function. */
    arguments: Record<string, unknown>
}

/**
 * A single message in the conversation history exchanged between participants.
 *
 * @example
 * ```ts
 * const userMsg: Message = { role: 'user', content: 'Hello!' }
 * const toolResult: Message = {
 *   role: 'tool',
 *   content: '{"temp": 22}',
 *   toolCallId: 'call_abc123',
 * }
 * ```
 */
export interface Message {
    /** The role of the message author. */
    role: Role
    /** The text content of the message, or `null` when the assistant response consists solely of tool calls. */
    content: string | null
    /** Tool calls requested by the assistant in this message, if any. */
    toolCalls?: ToolCall[]
    /** The ID of the tool call this message is a response to (only for `role: 'tool'`). */
    toolCallId?: string
    /** An optional display name for the message author. */
    name?: string
    /**
     * Image data attached to a tool result message.
     * When present, providers format this as a multimodal content block
     * alongside the text content.
     */
    image?: ImageResult
}
